In [1]:
from __future__ import division #, print_function
import sys
import os
import csv
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from fiona.crs import from_epsg
import geopandas as gp
import shapely as shp
from geopandas.tools import sjoin
from shapely.geometry import Point

import pylab as pl
%pylab inline

#import seaborn
#from scipy.optimize import curve_fit, minimize

Populating the interactive namespace from numpy and matplotlib

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['datetime']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

In [2]:
#yt_1301 = pd.read_csv('data_raw_yellow/yellow_201601.csv')
#yt_1302 = pd.read_csv('data_raw_yellow/yellow_201602.csv')
#yt_1303 = pd.read_csv('data_raw_yellow/yellow_201603.csv')
#yt_1304 = pd.read_csv('data_raw_yellow/yellow_201604.csv')
#yt_1305 = pd.read_csv('data_raw_yellow/yellow_201605.csv')
#yt_1306 = pd.read_csv('data_raw_yellow/yellow_201606.csv')
#yt_1307 = pd.read_csv('data_raw_yellow/yellow_201607.csv')
yt_1308 = pd.read_csv('data_raw_yellow/yellow_201308.csv')
yt_1309 = pd.read_csv('data_raw_yellow/yellow_201309.csv')
yt_1310 = pd.read_csv('data_raw_yellow/yellow_201310.csv')
yt_1311 = pd.read_csv('data_raw_yellow/yellow_201311.csv')
yt_1312 = pd.read_csv('data_raw_yellow/yellow_201312.csv')

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
yt_1401 = pd.read_csv('data_raw_yellow/yellow_201401.csv')
yt_1402 = pd.read_csv('data_raw_yellow/yellow_201402.csv')
yt_1403 = pd.read_csv('data_raw_yellow/yellow_201403.csv')
yt_1404 = pd.read_csv('data_raw_yellow/yellow_201404.csv')
yt_1405 = pd.read_csv('data_raw_yellow/yellow_201405.csv')
yt_1406 = pd.read_csv('data_raw_yellow/yellow_201406.csv')
yt_1407 = pd.read_csv('data_raw_yellow/yellow_201407.csv')
yt_1408 = pd.read_csv('data_raw_yellow/yellow_201408.csv')
yt_1409 = pd.read_csv('data_raw_yellow/yellow_201409.csv')
yt_1410 = pd.read_csv('data_raw_yellow/yellow_201410.csv')
yt_1411 = pd.read_csv('data_raw_yellow/yellow_201411.csv')
yt_1412 = pd.read_csv('data_raw_yellow/yellow_201412.csv')

In [4]:
yt_1501 = pd.read_csv('data_raw_yellow/yellow_201501.csv')
yt_1502 = pd.read_csv('data_raw_yellow/yellow_201502.csv')
yt_1503 = pd.read_csv('data_raw_yellow/yellow_201503.csv')
yt_1504 = pd.read_csv('data_raw_yellow/yellow_201504.csv')
yt_1505 = pd.read_csv('data_raw_yellow/yellow_201505.csv')
yt_1506 = pd.read_csv('data_raw_yellow/yellow_201506.csv')
yt_1507 = pd.read_csv('data_raw_yellow/yellow_201507.csv')
yt_1508 = pd.read_csv('data_raw_yellow/yellow_201508.csv')
yt_1509 = pd.read_csv('data_raw_yellow/yellow_201509.csv')
yt_1510 = pd.read_csv('data_raw_yellow/yellow_201510.csv')
yt_1511 = pd.read_csv('data_raw_yellow/yellow_201511.csv')
yt_1512 = pd.read_csv('data_raw_yellow/yellow_201512.csv')

In [5]:
yt_1601 = pd.read_csv('data_raw_yellow/yellow_201601.csv')
yt_1602 = pd.read_csv('data_raw_yellow/yellow_201602.csv')
yt_1603 = pd.read_csv('data_raw_yellow/yellow_201603.csv')
yt_1604 = pd.read_csv('data_raw_yellow/yellow_201604.csv')
yt_1605 = pd.read_csv('data_raw_yellow/yellow_201605.csv')
yt_1606 = pd.read_csv('data_raw_yellow/yellow_201606.csv')
#yt_1607 = pd.read_csv('data_raw_yellow/yellow_201607.csv')
#yt_1608 = pd.read_csv('data_raw_yellow/yellow_201608.csv')
#yt_1609 = pd.read_csv('data_raw_yellow/yellow_201609.csv')
#yt_1610 = pd.read_csv('data_raw_yellow/yellow_201610.csv')
#yt_1611 = pd.read_csv('data_raw_yellow/yellow_201611.csv')
#yt_1612 = pd.read_csv('data_raw_yellow/yellow_201612.csv')

##### enter CB station ID ("choice") and radius ("radius").  Use Notebook 8 to process buffers in bulk.

In [27]:

choice = 3142
radius = 450

In [28]:
station_bounds = pd.read_csv('data_pre_cb/deployment_bounds.csv')
station_bounds.drop(['Unnamed: 0'],axis=1,inplace=True)
station_bounds[station_bounds.station_id == choice]

,boro_name,deployment,station_id,min_lon,min_lat,max_lon,max_lat
163,Manhattan,9/2/2015 11:51:59,3142,-73.962637,40.759937,-73.959244,40.762517

In [29]:
bufs_3 = gp.GeoDataFrame.from_file('data_pre_cb/bufs_3.shp')
bufs_3.crs = {'init': 'epsg:2263', 'no_defs': True}
bufs_3 = bufs_3.to_crs(epsg=2263)
bufs_3.crs

bufs_c = bufs_3[(bufs_3.station_id == choice) & (bufs_3.radius == radius)]
bufs_c.reset_index(drop=True, inplace = True)
bufs_c

,boro_name,deployment,geometry,radius,station_id
0,Manhattan,9/2/2015 11:51:59,"POLYGON ((995520.5810160585 216614.8059189046,...",450,3142

In [30]:
station_bounds[station_bounds.station_id == choice]

,boro_name,deployment,station_id,min_lon,min_lat,max_lon,max_lat
163,Manhattan,9/2/2015 11:51:59,3142,-73.962637,40.759937,-73.959244,40.762517

In [31]:
station_bounds[station_bounds.station_id == choice].index[0]

163

##### important... enter index number ("idxx") of corresponding station:

In [32]:
idxx = 163
station_bounds.iloc[idxx][2]

3142

In [33]:
def choose_col_pu_2013(pu_data_2013):
    pu_2013 = pu_data_2013[['pickup_datetime','dropoff_datetime','pickup_longitude','pickup_latitude','trip_distance']]
    pu_2013['num_trips'] = pu_data_2013['trip_distance']
    pu_2013.rename(columns={'pickup_datetime':'pu_time','dropoff_datetime':'do_time',
                            'pickup_longitude':'pu_lon', 'pickup_latitude':'pu_lat'},
              inplace=True)
    return pu_2013


def choose_col_pu_2014(pu_data_2014):
    pu_2014 = pu_data_2014[[' pickup_datetime',' dropoff_datetime',' pickup_longitude',' pickup_latitude',' trip_distance']]
    pu_2014['num_trips'] = pu_data_2014[' trip_distance']
    pu_2014.rename(columns={' pickup_datetime':'pu_time',' dropoff_datetime':'do_time',
                            ' pickup_longitude':'pu_lon', ' pickup_latitude':'pu_lat', ' trip_distance':'trip_distance'},
              inplace=True)
    return pu_2014

def choose_col_pu_2015(pu_data_2015):
    pu_2015 = pu_data_2015[['tpep_pickup_datetime','tpep_dropoff_datetime','pickup_longitude','pickup_latitude','trip_distance']]
    pu_2015['num_trips'] = pu_data_2015['trip_distance']
    pu_2015.rename(columns={'tpep_pickup_datetime':'pu_time','tpep_dropoff_datetime':'do_time',
                            'pickup_longitude':'pu_lon', 'pickup_latitude':'pu_lat'},
              inplace=True)
    return pu_2015

def choose_col_pu_2016(pu_data_2016):
    pu_2016 = pu_data_2016[['tpep_pickup_datetime','tpep_dropoff_datetime','pickup_longitude','pickup_latitude','trip_distance']]
    pu_2016['num_trips'] = pu_data_2016['trip_distance']
    pu_2016.rename(columns={'tpep_pickup_datetime':'pu_time','tpep_dropoff_datetime':'do_time',
                            'pickup_longitude':'pu_lon', 'pickup_latitude':'pu_lat'},
              inplace=True)
    return pu_2016


#######################

def trim_bounds_pu(pu_data):
    
    #min_lon = station_bounds[station_bounds['station_id'] == bounds]['min_lon'][0]
    #max_lon = station_bounds[station_bounds['station_id'] == bounds]['max_lon'][0]
    #min_lat = station_bounds[station_bounds['station_id'] == bounds]['min_lat'][0]
    #max_lat = station_bounds[station_bounds['station_id'] == bounds]['max_lat'][0]

    startTime = datetime.datetime.now()

    #b = 430
    
    min_lon = station_bounds.iloc[idxx][3]
    min_lat = station_bounds.iloc[idxx][4] 
    max_lon = station_bounds.iloc[idxx][5]
    max_lat = station_bounds.iloc[idxx][6]    
    
    pu_trim = pu_data[(pu_data['pu_lon'] > min_lon) & (pu_data['pu_lon'] < max_lon) &
                      (pu_data['pu_lat'] > min_lat) & (pu_data['pu_lat'] < max_lat)]
    

    geometry = [Point(xy) for xy in zip(pu_trim['pu_lon'], pu_trim['pu_lat'])]
    crs = {'init': 'epsg:4326', 'no_defs': True}
#    crs = {'init': 'epsg:2263', 'no_defs': True}
    pu_data_points = gp.GeoDataFrame(pu_trim, crs=crs, geometry=geometry)       
    pu_data_points = pu_data_points.to_crs(epsg=2263)
    
    print datetime.datetime.now() - startTime, "Shrunk Dataset & Created Points"

    return pu_data_points

#############################

def join_pu(rides_pu):
    
    startTime = datetime.datetime.now()

    mg = sjoin(rides_pu, bufs_c, how='inner', op='within')
    
    print datetime.datetime.now() - startTime,"Spatial join done"

    return mg
    

    
def trim_by_date_pu(pu_dt):

    startTime = datetime.datetime.now()
        
    pu_dt['start'] = pd.to_datetime(pu_dt['pu_time'])
    pu_dt['end'] = pd.to_datetime(pu_dt['do_time'])
    pu_dt['trip_time'] = (pu_dt['end'] - pu_dt['start']).dt.total_seconds()/60
    pu_dt.reset_index(drop=True, inplace = True)

    print datetime.datetime.now() - startTime,"Made trip time"
    
    return pu_dt

    
    
def agg_pu(pu_ag):
    
    startTime = datetime.datetime.now()

    pu_ag['pu_date'] = pu_ag['start'].dt.date
    data_pu_ag = pu_ag[['pu_date','station_id','radius','num_trips','trip_distance','trip_time']].sort(['station_id','radius','pu_date'])
    data_pu_ag.reset_index(inplace = True)

    data_pu_ag = data_pu_ag.groupby(['station_id','radius','pu_date']).agg({'num_trips': "count", 'trip_distance':"mean",'trip_time':"mean"})
    
    print datetime.datetime.now() - startTime,"Aggregated by date"
    
    data_pu_ag.reset_index(inplace = True)

    return data_pu_ag

def run_all_13(taxi_data):
    txd = choose_col_pu_2013(taxi_data)
    txd = trim_bounds_pu(txd)
    txd = join_pu(txd)
    txd = trim_by_date_pu(txd)
    txd = agg_pu(txd)
    
    return txd

def run_all_14(taxi_data):
    txd = choose_col_pu_2014(taxi_data)
    txd = trim_bounds_pu(txd)
    txd = join_pu(txd)
    txd = trim_by_date_pu(txd)
    txd = agg_pu(txd)
    
    return txd

def run_all_15(taxi_data):
    txd = choose_col_pu_2015(taxi_data)
    txd = trim_bounds_pu(txd)
    txd = join_pu(txd)
    txd = trim_by_date_pu(txd)
    txd = agg_pu(txd)
    
    return txd

def run_all_16(taxi_data):
    txd = choose_col_pu_2016(taxi_data)
    txd = trim_bounds_pu(txd)
    txd = join_pu(txd)
    txd = trim_by_date_pu(txd)
    txd = agg_pu(txd)
    
    return txd

In [15]:
ytx_pu = pd.DataFrame()

In [34]:
#ytx_1301_pu = run_all(yt_1301)
#ytx_1302_pu = run_all(yt_1302)
#ytx_1303_pu = run_all(yt_1303)
#ytx_1304_pu = run_all(yt_1304)
#ytx_1305_pu = run_all(yt_1305)
#ytx_1306_pu = run_all(yt_1306)
#ytx_1307_pu = run_all(yt_1307)
ytx_1308_pu = run_all_13(yt_1308)
ytx_1309_pu = run_all_13(yt_1309)
ytx_1310_pu = run_all_13(yt_1310)
ytx_1311_pu = run_all_13(yt_1311)
ytx_1312_pu = run_all_13(yt_1312)


ytx_1401_pu = run_all_14(yt_1401)
ytx_1402_pu = run_all_14(yt_1402)
ytx_1403_pu = run_all_14(yt_1403)
ytx_1404_pu = run_all_14(yt_1404)
ytx_1405_pu = run_all_14(yt_1405)
ytx_1406_pu = run_all_14(yt_1406)
ytx_1407_pu = run_all_14(yt_1407)
ytx_1408_pu = run_all_14(yt_1408)
ytx_1409_pu = run_all_14(yt_1409)
ytx_1410_pu = run_all_14(yt_1410)
ytx_1411_pu = run_all_14(yt_1411)
ytx_1412_pu = run_all_14(yt_1412)

ytx_1501_pu = run_all_15(yt_1501)
ytx_1502_pu = run_all_15(yt_1502)
ytx_1503_pu = run_all_15(yt_1503)
ytx_1504_pu = run_all_15(yt_1504)
ytx_1505_pu = run_all_15(yt_1505)
ytx_1506_pu = run_all_15(yt_1506)
ytx_1507_pu = run_all_15(yt_1507)
ytx_1508_pu = run_all_15(yt_1508)
ytx_1509_pu = run_all_15(yt_1509)
ytx_1510_pu = run_all_15(yt_1510)
ytx_1511_pu = run_all_15(yt_1511)
ytx_1512_pu = run_all_15(yt_1512)


ytx_1601_pu = run_all_16(yt_1601)
ytx_1602_pu = run_all_16(yt_1602)
ytx_1603_pu = run_all_16(yt_1603)
ytx_1604_pu = run_all_16(yt_1604)
ytx_1605_pu = run_all_16(yt_1605)
ytx_1606_pu = run_all_16(yt_1606)

ytx_pu = ytx_pu.append(ytx_1308_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1309_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1310_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1311_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1312_pu, ignore_index=True)

ytx_pu = ytx_pu.append(ytx_1401_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1402_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1403_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1404_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1405_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1406_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1407_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1408_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1409_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1410_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1411_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1412_pu, ignore_index=True)

ytx_pu = ytx_pu.append(ytx_1501_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1502_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1503_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1504_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1505_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1506_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1507_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1508_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1509_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1510_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1511_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1512_pu, ignore_index=True)

ytx_pu = ytx_pu.append(ytx_1601_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1602_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1603_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1604_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1605_pu, ignore_index=True)
ytx_pu = ytx_pu.append(ytx_1606_pu, ignore_index=True)

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

0:00:04.599304 Shrunk Dataset & Created Points
0:00:06.214676 Spatial join done
0:00:00.036282 Made trip time
0:00:00.120996 Aggregated by date

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:101: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

0:00:05.519701 Shrunk Dataset & Created Points
0:00:06.902834 Spatial join done
0:00:00.043059 Made trip time
0:00:00.143865 Aggregated by date
0:00:06.059430 Shrunk Dataset & Created Points
0:00:07.338162 Spatial join done
0:00:00.051978 Made trip time
0:00:00.578689 Aggregated by date
0:00:05.895159 Shrunk Dataset & Created Points
0:00:07.106661 Spatial join done
0:00:00.048779 Made trip time
0:00:00.149109 Aggregated by date
0:00:06.077346 Shrunk Dataset & Created Points
0:00:07.678974 Spatial join done
0:00:00.044986 Made trip time
0:00:00.580869 Aggregated by date

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0:00:05.858645 Shrunk Dataset & Created Points
0:00:07.076424 Spatial join done
0:00:00.046121 Made trip time
0:00:00.149458 Aggregated by date
0:00:04.817072 Shrunk Dataset & Created Points
0:00:06.608732 Spatial join done
0:00:00.039384 Made trip time
0:00:00.132305 Aggregated by date
0:00:05.883245 Shrunk Dataset & Created Points
0:00:06.970027 Spatial join done
0:00:00.045854 Made trip time
0:00:00.147281 Aggregated by date
0:00:05.812429 Shrunk Dataset & Created Points
0:00:06.814315 Spatial join done
0:00:00.041762 Made trip time
0:00:00.140031 Aggregated by date
0:00:05.956011 Shrunk Dataset & Created Points
0:00:07.236509 Spatial join done
0:00:00.043746 Made trip time
0:00:00.542970 Aggregated by date
0:00:05.767993 Shrunk Dataset & Created Points
0:00:06.746773 Spatial join done
0:00:00.045394 Made trip time
0:00:00.149154 Aggregated by date
0:00:04.838404 Shrunk Dataset & Created Points
0:00:06.513698 Spatial join done
0:00:00.037777 Made trip time
0:00:00.131432 Aggregated by date
0:00:04.699718 Shrunk Dataset & Created Points
0:00:06.408628 Spatial join done
0:00:00.042756 Made trip time
0:00:00.133059 Aggregated by date
0:00:04.953308 Shrunk Dataset & Created Points
0:00:06.932849 Spatial join done
0:00:00.043852 Made trip time
0:00:00.149949 Aggregated by date
0:00:05.867045 Shrunk Dataset & Created Points
0:00:07.126995 Spatial join done
0:00:00.048017 Made trip time
0:00:00.159908 Aggregated by date
0:00:05.433052 Shrunk Dataset & Created Points
0:00:06.598650 Spatial join done
0:00:00.042860 Made trip time
0:00:00.144997 Aggregated by date
0:00:05.809905 Shrunk Dataset & Created Points
0:00:07.107629 Spatial join done
0:00:00.046725 Made trip time
0:00:00.159332 Aggregated by date

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0:00:04.992045 Shrunk Dataset & Created Points
0:00:06.815950 Spatial join done
0:00:00.046545 Made trip time
0:00:00.136856 Aggregated by date
0:00:04.795764 Shrunk Dataset & Created Points
0:00:06.560203 Spatial join done
0:00:00.043501 Made trip time
0:00:00.136828 Aggregated by date
0:00:05.650678 Shrunk Dataset & Created Points
0:00:06.802630 Spatial join done
0:00:00.046979 Made trip time
0:00:00.148071 Aggregated by date
0:00:04.942380 Shrunk Dataset & Created Points
0:00:06.755362 Spatial join done
0:00:00.048952 Made trip time
0:00:00.143535 Aggregated by date
0:00:05.224063 Shrunk Dataset & Created Points
0:00:06.965470 Spatial join done
0:00:00.046140 Made trip time
0:00:00.154057 Aggregated by date
0:00:04.895460 Shrunk Dataset & Created Points
0:00:06.612229 Spatial join done
0:00:00.040385 Made trip time
0:00:00.130791 Aggregated by date
0:00:04.405625 Shrunk Dataset & Created Points
0:00:06.119222 Spatial join done
0:00:00.035843 Made trip time
0:00:00.118896 Aggregated by date
0:00:04.339064 Shrunk Dataset & Created Points
0:00:05.866964 Spatial join done
0:00:00.039221 Made trip time
0:00:00.114934 Aggregated by date
0:00:04.394303 Shrunk Dataset & Created Points
0:00:05.866418 Spatial join done
0:00:00.033833 Made trip time
0:00:00.118699 Aggregated by date
0:00:04.869953 Shrunk Dataset & Created Points
0:00:06.561933 Spatial join done
0:00:00.037225 Made trip time
0:00:00.124964 Aggregated by date
0:00:04.381069 Shrunk Dataset & Created Points
0:00:05.905191 Spatial join done
0:00:00.037339 Made trip time
0:00:00.114117 Aggregated by date
0:00:04.041643 Shrunk Dataset & Created Points
0:00:05.007313 Spatial join done
0:00:00.032422 Made trip time
0:00:00.508857 Aggregated by date

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0:00:04.444611 Shrunk Dataset & Created Points
0:00:05.987332 Spatial join done
0:00:00.032319 Made trip time
0:00:00.118898 Aggregated by date
0:00:04.434465 Shrunk Dataset & Created Points
0:00:05.975164 Spatial join done
0:00:00.035129 Made trip time
0:00:00.113025 Aggregated by date
0:00:04.718601 Shrunk Dataset & Created Points
0:00:06.278148 Spatial join done
0:00:00.035789 Made trip time
0:00:00.170044 Aggregated by date
0:00:04.727513 Shrunk Dataset & Created Points
0:00:06.415830 Spatial join done
0:00:00.035818 Made trip time
0:00:00.123608 Aggregated by date
0:00:04.763370 Shrunk Dataset & Created Points
0:00:06.405190 Spatial join done
0:00:00.039328 Made trip time
0:00:00.126942 Aggregated by date
0:00:04.510144 Shrunk Dataset & Created Points
0:00:06.021994 Spatial join done
0:00:00.035219 Made trip time
0:00:00.116689 Aggregated by date

In [35]:
ytx_pu

      station_id  radius     pu_date  num_trips  trip_distance  trip_time
0           3142     150  2013-08-01        155       2.745419  12.049247
1           3142     150  2013-08-02        104       2.895192  11.178686
2           3142     150  2013-08-03         84       2.803571   9.538690
3           3142     150  2013-08-04         70       3.275714  10.580714
4           3142     150  2013-08-05        205       2.218439   9.200000
5           3142     150  2013-08-06        202       2.161436   9.597855
6           3142     150  2013-08-07        190       2.341263   9.916754
7           3142     150  2013-08-08        246       2.571667  10.194377
8           3142     150  2013-08-09        236       2.229068  10.141455
9           3142     150  2013-08-10        195       2.687897  10.326581
10          3142     150  2013-08-11         79       2.328861   8.379747
11          3142     150  2013-08-12        214       2.031542   9.919081
12          3142     150  2013-08-13        199       1.946281  10.090787
13          3142     150  2013-08-14        201       2.259055  10.910531
14          3142     150  2013-08-15        214       2.211168  11.352259
15          3142     150  2013-08-16        179       2.673743  12.288547
16          3142     150  2013-08-17        164       2.917500  10.854573
17          3142     150  2013-08-18        161       2.608509   8.824741
18          3142     150  2013-08-19        222       2.428378  10.027778
19          3142     150  2013-08-20        182       2.457912  10.899908
20          3142     150  2013-08-21        204       2.437402  11.003513
21          3142     150  2013-08-22        208       2.279183  10.897196
22          3142     150  2013-08-23        210       2.394762   9.914286
23          3142     150  2013-08-24        182       2.455000   9.456685
24          3142     150  2013-08-25        178       2.514831   8.820412
25          3142     150  2013-08-26        180       2.223278  10.139074
26          3142     150  2013-08-27        176       2.524205  11.082008
27          3142     150  2013-08-28        178       2.199888  10.604775
28          3142     150  2013-08-29        174       2.718678  12.024425
29          3142     150  2013-08-30        199       2.552362  10.861809
...          ...     ...         ...        ...            ...        ...
3165        3142     450  2016-06-01        927       2.146580  12.944408
3166        3142     450  2016-06-02        979       2.210838  11.536704
3167        3142     450  2016-06-03        996       2.195683  11.918390
3168        3142     450  2016-06-04       1077       2.458050  14.678103
3169        3142     450  2016-06-05        896       2.203605   9.443490
3170        3142     450  2016-06-06        887       2.182740  14.016911
3171        3142     450  2016-06-07        950       2.257905  13.334404
3172        3142     450  2016-06-08       1036       2.161139  13.736181
3173        3142     450  2016-06-09        994       2.270795  11.963028
3174        3142     450  2016-06-10       1017       2.211927  11.298820
3175        3142     450  2016-06-11        942       2.322452   9.631918
3176        3142     450  2016-06-12        782       2.539757   9.521888
3177        3142     450  2016-06-13        833       2.298643  10.360984
3178        3142     450  2016-06-14        903       2.204839  12.047711
3179        3142     450  2016-06-15        953       2.083158  11.004879
3180        3142     450  2016-06-16       1088       2.343116  16.495083
3181        3142     450  2016-06-17       1003       2.278265  14.944001
3182        3142     450  2016-06-18        846       2.309326  11.513219
3183        3142     450  2016-06-19        685       2.370876   8.797567
3184        3142     450  2016-06-20        859       2.107742  11.676911
3185        3142     450  2016-06-21        942       2.129480  12.430573
3186        3142     450  2016-06-22        921       2.244169  12.273000
3187        3142     450  2016-06-23        947       2.174720  12.784530
3188        3142     450  2016-06-24        943       2.309629  11.216437
3189        3142     450  2016-06-25        891       2.324613  13.544482
3190        3142     450  2016-06-26        816       2.299350  11.005617
3191        3142     450  2016-06-27        833       2.244766  12.201641
3192        3142     450  2016-06-28        865       2.079838  10.918574
3193        3142     450  2016-06-29        879       2.179090  11.880470
3194        3142     450  2016-06-30        951       2.382902  16.122415

[3195 rows x 6 columns]

In [37]:
yellow_3142_pu = ytx_pu
yellow_3142_pu.to_csv('data_pre_yellow/yellow_3142_pu.csv')